[project]
name = "wifi-setup-rpi-zero2w"
version = "0.1.0"
description = "A Flask-based web portal for configuring WiFi on Raspberry Pi Zero 2W"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
